### ISSUE TITLE
Is there a way to generate (Keras) code form a partially completed model?

### ISSUE THREAD

**Issue by laefsky** [rahular/darviz-issues#11]
If a model is for instance temporarily lacking a data source or that source is in some other format than Pickle and one wishes to fill in code in Keras is there a way to generate code from a prtially completed design?

**Comment by rahular** [comment]
For now, you will have to change the code manually.

**Comment by laefsky** [comment]
So there is no way to generate code unless the model is complete and correct??

**Comment by goodboyanush** [comment]
@laefsky no, to generate a code the model has to be correct and complete.

You can find more information here: https://dataplatform.cloud.ibm.com/docs/content/analyze-data/ml-canvas-nnd-intro.html
