### ISSUE TITLE
Consider the Use Case Where You Wish to Use Darviz to Design NN for Own Data

### ISSUE THREAD

**Issue by laefsky** [rahular/darviz-issues#13]
In preparation for using Darviz as a design tool for NN's to be processed in Keras/TF on my own data sets I generated Keras Code with the MNIST Example from your site with Model A. I then loaded it to my Ubuntu Docker Instance of Keras/TF and attempted to edit the code to take the MNIST image from Keras itself.
I would like to use Darviz as a tool to design efficient NN's but incorporate calculations on my own data sets.  What would you recommend as the best approach and how can I best get Keras code to be edited for my own data sets and formats stored on the machine running compilation to Tensorflow?

**Comment by goodboyanush** [comment]
@laefsky you should find more information on this here now: https://dataplatform.cloud.ibm.com/docs/content/analyze-data/ml-canvas-nnd-intro.html
