### ISSUE TITLE
Pytorch 

### ISSUE THREAD

**Issue by amarazad** [rahular/darviz-issues#14]
Do you have plans to support pytorch. It might be a good idea as Pytorch is gaining popularity in DL very rapidly.

**Comment by rahular** [comment]
We definitely have it in our road map. But we are focusing on hardening our current set of features in the next couple of releases.

**Comment by goodboyanush** [comment]
@amarazad we support PyTorch now. For more information: https://dataplatform.cloud.ibm.com/docs/content/analyze-data/ml-canvas-nnd-intro.html
