### ISSUE TITLE
VGG 19

### ISSUE THREAD

**Issue by AdityaSoni19031997** [rahular/darviz-issues#16]
First of all..

Thank you !!!!!!! for building such an awesome ide to make life simple...

> Why aren't the original model with the dropout layers and all is there?(original is original)

[like this one](https://gist.github.com/baraldilorenzo/8d096f48a1be4a2d660d)

> Also after generating the code from the ide it will be much better if the layer retains their name as 
   implied by the layer..

this

`ReLU_2 = Activation('relu', name = 'ReLU.7e9f24ad')(Convolution2D_1)`

to 

``ReLU_2 = Activation('relu', name = 'ReLU_2')(Convolution2D_1)`` (removed the hash_id)

I know its not necessary but it will help in tensorboard while visualisation..

**Comment by goodboyanush** [comment]
@AdityaSoni19031997 Thanks for your comments and inputs. 

We will work on this and get back to you as soon as we finish it

**Comment by AdityaSoni19031997** [comment]
That's great!!!

> Also please add a tab to hide the right 

> Section in the Design where we it's

> displayed saved model , error and all

> Doing so will add to the design space

> more and the user will be able to use it

> as per discretion.. 

_Sent from my Lenovo A6020a40 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by goodboyanush** [comment]
You could currently drag the bar separating the two sections and minimize it.

**Comment by AdityaSoni19031997** [comment]
Why not make relu the default activation function whenever we select conv2D layer..
Because everyone follows that way..

_Sent from my Lenovo A6020a40 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rahular** [comment]
@AdityaSoni19031997 we will add it to our bucketlist of upcoming features.

**Comment by goodboyanush** [comment]
@AdityaSoni19031997 you can find more information on this here: https://dataplatform.cloud.ibm.com/docs/content/analyze-data/ml-canvas-nnd-intro.html
