### ISSUE TITLE
ImageData nodes cannot be saved, Create SourceCode does not work

### ISSUE THREAD

**Issue by steftux** [rahular/darviz-issues#18]
Error1:
Every time I try to save an ImageData node and use a "Pre-exisiting" model (yes that typo is there as well...) such as MINIST, CIFAR10 or others, the node will NOT be saved but it will switch back to Datasource: "Create New".
So I cannot run any model.

Error2:
Also when I try to "Create Source Code" it just tells me to 
"Please create a design model to be able to create a job." (well I already did before...)

Question:
Also if I export a model to a model.dz I get a file but I have no idea what to do with it from there. What do I do with it?

**Comment by goodboyanush** [comment]
Hi @steftux . Thanks for your questions

Error1:
Only the dropdown box will read as "Create New". However, the data properties in the form fields below it will be filled and retained as per your choice. The "Pre-existing" data model is used only to fill the form fields of data properties.

Error2:
Source code can be generated for a design only if it is error free. Please open your design and on the right side "Errors" tab, please check for the errors. FIx these errors and then you should be able to generate the source code.

Question:
This feature is meant for sharing the design. Once you have create a design, you could download the design as a .dz file. You can share this .dz file with your colleagues through email. And they should be able to "import" the same design into their design space.

Hope this clarifies your questions.
