### ISSUE TITLE
Please OPEN SOURCE  DARVIZ IDE on github so that we can contribute , extend it and develop it further 

### ISSUE THREAD

**Issue by developeralgo8888** [rahular/darviz-issues#19]
Please Open Source  DARVIZ   IDE on github so that we can contribute , extend it and develop it further.  Since it runs on Node-RED and Node.js and currently uses Keras to support /wrap/abstract  Tensorflow, Theano and Caffe as a backend.  We love it but without it being Open Sourced then very few developers will participate and such novel idea will just die . I don't want it to die but i want to promote it because it brings developers together to extend it.  I am Tinkerer and i like to develop and code various AI models but i believe we can quickly extend and contribute  to Darviz IDE for a much Larger adoption. 

Google made a smart move and out sourced Tensorflow and look how quickly it was adopted by developers and list goes on,  Keras , Caffe , MXNet , and others.

The Mantra for developers in this century is colloboration using Open Source.  or risk a good idea just dying very quickly .

**Comment by goodboyanush** [comment]
@developeralgo8888 Thanks a lot for your honest opinion and enthusiasm to tinker around with DARVIZ!

We are surely working towards the direction of making DARVIZ open source, as much as possible. We will surely post here and get back to you, whenever we have some updates in this thread.

Once again, we appreciate your passion towards open sourcing the system. We will be keen on hearing on more of your ideas or hacks you would want to play around with DARVIZ

**Comment by developeralgo8888** [comment]
If you need fast track contributions and development then you need to open source the same way Google, Facebook, Uber, IBM  , Keras , etc -- the reason those libraries or platform are progressing pretty fast with a huge user base of developers is because they are Open Source . No developer or company want to be locked into contractual license or fee structure obligations. As software Engineer i have worked for Google , Cisco, IBM  and others . The Trend is  " As software developer you need to have rapid development of your library and the only way you do that in an affordable cost is through Open Source " . I want to extend your library to deal with Time-Series datasets and additional new Nets , layers and models  but i can't if its not " OPEN SOURCED"

**Comment by developeralgo8888** [comment]
Doesn't seem that this IBM team is interested in any developer's feedback . if  your are a Developer , an AI engineer, Machine Learning expert that wanted to extend this Library , i think its becoming clear that they are not interested --- they are looking payment model for this library -- Why waste money when you can get better Open source products out in the market. Move On from this. There are better products out there , Microsoft Azure Machine Learning Studio  and Deep Learning Studio. They do a better job.
