### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by sycdlcrain** [rahular/darviz-issues#20]
I am playing around with the interface, but I can't figure out how to delete a component. Because it's an alpha version, I'm not sure if it's not implemented or I'm just missing it.

**Comment by goodboyanush** [comment]
A simple delete button from the keyboard should work!

**Comment by goodboyanush** [comment]
@sycdlcrain you can now find more information regarding this here: https://dataplatform.cloud.ibm.com/docs/content/analyze-data/ml-canvas-nnd-intro.html
