### ISSUE TITLE
Compare & Contrast Darviz with Barista https://www.uni-muenster.de/PRIA/Barista/

### ISSUE THREAD

**Issue by laefsky** [rahular/darviz-issues#21]
As a graphical tool for Deep Learning Could You Compare the Features and Limitations of Darviz vs. the Barista project for Cafee out of Muenster

**Comment by goodboyanush** [comment]
@laefsky the quick point would be that Barista is meant as a graphical tool only for the Caffe library

The deep learning IDE that we designed is library agnostic. It acts as graphical front ending tool for Caffe, Keras, Tensorflow, and PyTorch.

You can find more information here: https://dataplatform.cloud.ibm.com/docs/content/analyze-data/ml-canvas-nnd-intro.html
