### ISSUE TITLE
I can't go to the website of dlide.mybluemix.net

### ISSUE THREAD

**Issue by ParsonsZeng** [rahular/darviz-issues#23]
![image](https://user-images.githubusercontent.com/26595294/42626189-3efd8810-85fc-11e8-8344-472ea0e1512b.png)
Is it some problem with the website? https://dlide.mybluemix.net/

**Comment by goodboyanush** [comment]
@ParsonsZeng Thanks for the message. 

we have moved DL-IDE into Watson Studio as Neural Network Modeller - https://dataplatform.cloud.ibm.com/docs/content/analyze-data/ml-canvas-nnd-intro.html

You can use Watson Studio here:  https://dataplatform.cloud.ibm.com/

Hope this helps.
