### ISSUE TITLE
darviz-git plus bluemix testing

### ISSUE THREAD

**Issue by rahular** [rahular/darviz-issues#4]
Please Ignore

Submitted by: panwarspam9@gmail.com

**Comment by laefsky** [comment]
How do I delete or edit a node right click doesn't offer options

**Comment by goodboyanush** [comment]
If you want to delete a node from workspace - you can simple select the node and press the delete button. 

If you want to edit the parameters of a node - do a double left click to get the options menu. 

Are you looking for any other edit operation on the node?
