### ISSUE TITLE
Cannot import name SigmoidCrossEntropyLoss

### ISSUE THREAD

**Issue by ghost** [rahular/darviz-issues#9]
Hi, when i tried to run the MNIST tutorial from TensorFlow, I had this issue "  File "Keras.py", line 14, in <module>
    from keras.layers import SigmoidCrossEntropyLoss, Activation, Input
ImportError: cannot import name SigmoidCrossEntropyLoss"

**Comment by ghost** [comment]
I'm running the model in Tensorflow (it is running normally). I just installed Keras using the Keras's website instructions. If i code "python" and "import keras" I have this message.  "import keras
Using TensorFlow backend.
Couldn't import dot_parser, loading of dot files will not be possible." I don't know well if Keras is working. But just to add information to help you to fix it. :)

**Comment by panwarnaveen9** [comment]
Hi, @RomuloThiago 

Thanks for raising the bug. 
We have resolved the issue. Please check and close the bug.

**Comment by ghost** [comment]
Thank you.
